name: buildimg

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'model'
        required: true
        default: 'DS3622xs+'
      revision:
        description: 'revision'
        required: true
        default: '7.2.2-72806'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build tinycore-redpill loader with lastest img
        id: build-loader
        run: |
          sudo apt update
          #sudo apt-get install grub2
          sudo apt-get install qemu-utils

          sudo mkdir /home/tc
          sudo mkdir /opt/output
          sudo cp -rf ./* /home/tc
          ls -ltr /home/tc
          
          LATESTURL="`curl --connect-timeout 5 -skL -w %{url_effective} -o /dev/null "https://github.com/PeterSuh-Q3/tinycore-redpill/releases/latest"`"
          TAG="${LATESTURL##*/}"
          echo "TAG is ${TAG}"
          curl -kLO# https://github.com/PeterSuh-Q3/tinycore-redpill/releases/download/${TAG}/tinycore-redpill.${TAG}.m-shell.img.gz
          gunzip tinycore-redpill.${TAG}.m-shell.img.gz          
          pwd
          ls -ltr
          echo "::set-output name=TAG::${TAG}"

          path=`pwd`

          LOOPX=$(sudo losetup -f)
          sudo losetup -P ${LOOPX} tinycore-redpill.${TAG}.m-shell.img
          sudo fdisk -l ${LOOPX}
          
          sudo ln -s ${LOOPX}p1 /mnt
          sudo ln -s ${LOOPX}p2 /mnt
          sudo ln -s ${LOOPX}p3 /mnt

          sudo losetup -d ${LOOPX}
          
          gzip -c tinycore-redpill.${TAG}.m-shell.img > /opt/output/tinycore-redpill.${TAG}.m-shell.img.gz

          qemu-img convert -f raw -O vmdk tinycore-redpill.${TAG}.m-shell.img tinycore-redpill.${TAG}.m-shell.vmdk
          gzip -c tinycore-redpill.${TAG}.m-shell.vmdk > /opt/output/tinycore-redpill.${TAG}.m-shell.vmdk.gz
          
          ls -ltr /opt/output
          
      - name: Upload MshellImage-${{ steps.build-loader.outputs.TAG }}
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: MshellImage-${{ steps.build-loader.outputs.TAG }}
          path: /opt/output
