name: Tar my.sh.gz

on:
   workflow_dispatch:

jobs:
  tar_compress_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Compress shell files
        run: |
          tar -zcvf my.sh.gz my myv functions.h myfunc.h menu.sh menu_m.sh ntp.sh sngen.sh macgen.sh edisk.sh rploader.sh custom_config.json modules.alias.4.json extractor.gz

      - name: Commit changes
        run: |
          git config --global user.name "PeterSuh-Q3"
          git config --global user.email dante9000@gmail.com
          git add my.sh.gz
          git commit -m "Update my.sh.gz"
          git push  
