name: Tar my.sh.gz

on:
  workflow_dispatch:

jobs:
  tar_compress_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Compress shell files
        id: remake-mydata-tgz
        run: |
          VERSION=v`cat rploader.sh | grep rploaderver= | cut -d\" -f2`
          echo "Version: ${VERSION}"
          echo "::set-output name=VERSION::${VERSION}"
          
          tar -zcvf my.sh.gz my myv functions.h myfunc.h menu.sh menu_m.sh ntp.sh sngen.sh macgen.sh edisk.sh rploader.sh custom_config.json modules.alias.4.json extractor.gz        
          mkdir -p ./mydata/home/tc/
          tar -zxvf mydata.tgz -C ./mydata/
          cp -vf my.sh.gz my myv functions.h myfunc.h menu.sh menu_m.sh ntp.sh sngen.sh macgen.sh edisk.sh rploader.sh custom_config.json modules.alias.4.json extractor.gz ./mydata/home/tc/
          tar -zcvf mydata.tgz -C ./mydata/ .
          
      - name: Commit changes
        run: |
          git config --global user.name "PeterSuh-Q3"
          git config --global user.email dante9000@gmail.com
          git add my.sh.gz mydata.tgz
          git commit -m "Update ${{ steps.remake-mydata-tgz.outputs.VERSION }} my.sh.gz, mydata.tgz"
          git push  
