name: Tar my.sh.gz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tar modules
        run: |
          tar -zcvf my.sh.gz my.sh myv.sh myfunc.h menu.sh menu_m.sh ntp.sh sngen.sh macgen.sh edisk.sh rploader.sh
          ./gitproc.sh my.sh.gz
